name: ECR
on:
  workflow_dispatch: {}

jobs:
  cdk_job:
    runs-on: ubuntu-latest
    name: ECR public action
    steps:
      - name: Set repo name
        id: repoName
        run: echo "::set-output name=reponame::$(echo public.ecr.aws/i2w6g4s0/legacy-unlight-docker)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ steps.repoName.outputs.reponame }}:latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login into registry
        run: aws ecr-public get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin public.ecr.aws
      - name: Build and Push to ECR public
        id: build-and-push
        run: |
          docker push ${{ steps.repoName.outputs.reponame }}:latest
